In [2]:
import numpy as np

In [4]:
type(np.array([1,2,3,4,5,6]))

numpy.ndarray

In [10]:
np.array([1,2,3,4,5,6.2])

array([1. , 2. , 3. , 4. , 5. , 6.2])

In [8]:
np.array([1,2,3,'4',5+8j,6])

array(['1', '2', '3', '4', '(5+8j)', '6'], dtype='<U11')

In [13]:
np.array([[1,2],[3,4],[5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
np.array([(1,2),(3,4),[5,6]]) # can use tuple also

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
np.array([[1,2],[3,4],[5,6,8]])

<ipython-input-18-c77122d2bc8b>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array([[1,2],[3,4],[5,6,8]])


array([list([1, 2]), list([3, 4]), list([5, 6, 8])], dtype=object)

In [14]:
np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]])

In [15]:
np.array([1,2,3,4,5,6],ndmin=3)

array([[[1, 2, 3, 4, 5, 6]]])

In [17]:
np.array([1,2,3,4,5,6],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [53]:
arr = np.array([1,2],dtype=[('a','<i4'),('b','<i8')])

In [54]:
type(arr[0])

numpy.void

In [55]:
type(arr[1])

numpy.void

In [28]:
ma = np.mat(np.array([[1,2],[3,5]])) # Converting to matrix

In [29]:
ma

matrix([[1, 2],
        [3, 5]])

In [23]:
np.matrix(np.array([[1,2],[3,5]])) #same as mat

matrix([[1, 2],
        [3, 5]])

In [32]:
l = [3,4,5,78,7]
arr = np.array(l)
arr

array([ 3,  4,  5, 78,  7])

In [25]:
np.asarray(l)

array([ 3,  4,  5, 78,  7])

In [26]:
np.asanyarray(l)

array([ 3,  4,  5, 78,  7])

In [30]:
issubclass(np.ndarray,np.matrix)

False

In [33]:
a = arr #Shallow copy
b = np.copy(arr) # Deep copy

In [34]:
arr[0] = 50

In [35]:
a

array([50,  4,  5, 78,  7])

In [36]:
b

array([ 3,  4,  5, 78,  7])

In [37]:
np.fromfunction(lambda i,j : i==j,(4,4)) # Creating ndarray using function 

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [40]:
a = lambda i,j : i==j

In [41]:
a(3,4)

False

In [42]:
a(4,4)

True

In [56]:
np.fromfunction(lambda i,j : i/j,(3,2)) 

<ipython-input-56-31b656cc142b>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i,j : i/j,(3,2))
<ipython-input-56-31b656cc142b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i,j : i/j,(3,2))


array([[nan,  0.],
       [inf,  1.],
       [inf,  2.]])

In [62]:
gen = (i*i for i in range(5))

In [63]:
def test(x):
    yield x

In [64]:
test(5)

<generator object test at 0x000002506846BF90>

In [66]:
gen

<generator object <genexpr> at 0x000002506846BF20>

In [67]:
np.fromiter(gen,dtype=int) # Creating ndarray using generator 

array([], dtype=int32)

In [68]:
np.fromiter(range(10),dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.fromstring('1,2,3,4,5,6',sep=',', dtype=int) # Creating ndarray using string 

array([1, 2, 3, 4, 5, 6])

In [80]:
arr = np.array([[1,2,3],[3,5,2],[4,5,6]])

In [81]:
arr.ndim

2

In [82]:
arr.size

9

In [83]:
arr.shape

(3, 3)

In [84]:
arr.dtype

dtype('int32')

In [85]:
arr = np.array([[[1,2,3],[3,5,2],[4,5,6]],[[1,2,3],[3,5,2],[4,5,6]]])

In [86]:
arr.ndim

3

In [89]:
arr.shape # 2 sets of 3x3 shape 2D data

(2, 3, 3)

In [90]:
arr.size

18

In [91]:
arr4 = np.array([[[[1,2,3],[3,5,2],[4,5,6]],[[1,2,3],[3,5,2],[4,5,6]]],[[[1,2,3],[3,5,2],[4,5,6]],[[1,2,3],[3,5,2],[4,5,6]]]])

In [92]:
arr4.shape

(2, 2, 3, 3)

In [93]:
range(6.0)

TypeError: 'float' object cannot be interpreted as an integer

In [105]:
np.arange(9,6.6,-.3) # due to float upper bound which is a continueos variable 6.60... upper bound is shown

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [99]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [107]:
np.linspace(1,2,5) # In between point 1 and 2 generating 5 data by dividing in 5 parts

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [111]:
np.linspace(2,4,4) 

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [115]:
np.linspace([2,4],4,endpoint=False,axis=1) # axis => 0 for x axis and 1 for y axis

array([[2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96],
       [4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  ]])

In [116]:
np.linspace([2,4],4,endpoint=False,axis=0)

array([[2.  , 4.  ],
       [2.04, 4.  ],
       [2.08, 4.  ],
       [2.12, 4.  ],
       [2.16, 4.  ],
       [2.2 , 4.  ],
       [2.24, 4.  ],
       [2.28, 4.  ],
       [2.32, 4.  ],
       [2.36, 4.  ],
       [2.4 , 4.  ],
       [2.44, 4.  ],
       [2.48, 4.  ],
       [2.52, 4.  ],
       [2.56, 4.  ],
       [2.6 , 4.  ],
       [2.64, 4.  ],
       [2.68, 4.  ],
       [2.72, 4.  ],
       [2.76, 4.  ],
       [2.8 , 4.  ],
       [2.84, 4.  ],
       [2.88, 4.  ],
       [2.92, 4.  ],
       [2.96, 4.  ],
       [3.  , 4.  ],
       [3.04, 4.  ],
       [3.08, 4.  ],
       [3.12, 4.  ],
       [3.16, 4.  ],
       [3.2 , 4.  ],
       [3.24, 4.  ],
       [3.28, 4.  ],
       [3.32, 4.  ],
       [3.36, 4.  ],
       [3.4 , 4.  ],
       [3.44, 4.  ],
       [3.48, 4.  ],
       [3.52, 4.  ],
       [3.56, 4.  ],
       [3.6 , 4.  ],
       [3.64, 4.  ],
       [3.68, 4.  ],
       [3.72, 4.  ],
       [3.76, 4.  ],
       [3.8 , 4.  ],
       [3.84, 4.  ],
       [3.88,

In [109]:
np.empty((3,4)) # generating random numbers

array([[0., 0., 1., 1.],
       [2., 2., 0., 1.],
       [0., 1., 0., 1.]])

In [118]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [119]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [120]:
d =  np.linspace(4,7,10)

In [121]:
d

array([4.        , 4.33333333, 4.66666667, 5.        , 5.33333333,
       5.66666667, 6.        , 6.33333333, 6.66666667, 7.        ])

In [122]:
d.shape

(10,)

In [124]:
d.reshape(10,1)

array([[4.        ],
       [4.33333333],
       [4.66666667],
       [5.        ],
       [5.33333333],
       [5.66666667],
       [6.        ],
       [6.33333333],
       [6.66666667],
       [7.        ]])

In [130]:
d.reshape(2,1,5)

array([[[4.        , 4.33333333, 4.66666667, 5.        , 5.33333333]],

       [[5.66666667, 6.        , 6.33333333, 6.66666667, 7.        ]]])

In [132]:
np.random.rand(3) # Normal Distribution between 0-1 with 3 elements 

array([0.95791433, 0.25465042, 0.90951509])

In [133]:
np.random.randn(3) # Standard Distribution

array([-1.51375017,  0.3686285 ,  0.41514484])

In [134]:
np.random.rand(2,3) # with 2x3 shape

array([[0.1487564 , 0.38836304, 0.36476935],
       [0.01377233, 0.7052864 , 0.86796116]])

In [147]:
np.random.randint(2,10,(4,4)) # Generating random int between given range

array([[5, 2, 3, 5],
       [2, 9, 9, 6],
       [7, 4, 6, 9],
       [9, 3, 2, 9]])

In [148]:
arr = np.random.randint(3,9,(3,3))

In [149]:
arr

array([[8, 8, 4],
       [4, 3, 7],
       [3, 7, 7]])

In [150]:
arr.reshape(2,3)

array([[8, 8, 4, 4, 3, 7, 3, 7, 7]])

In [155]:
arr.reshape(3,-2)

array([[8, 8, 4],
       [4, 3, 7],
       [3, 7, 7]])

In [158]:
arr.max()

8

In [157]:
arr.min()

3

In [159]:
arr = np.random.randint(4,100,(5,5))

In [160]:
arr

array([[85, 75, 16, 70, 32],
       [16, 34,  4, 76, 97],
       [81, 56, 35, 42, 81],
       [16, 97, 62, 42, 65],
       [53, 78, 30, 12, 54]])

In [162]:
arr[3:,3:] # all rows after 3 and only columns after 3 

array([[42, 65],
       [12, 54]])

In [163]:
arr[2,2] 

35

In [165]:
arr[:,[1,3]] # all rows and only 1 and 3 column 

array([[75, 70],
       [34, 76],
       [56, 42],
       [97, 42],
       [78, 12]])

In [166]:
arr>10

array([[ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [168]:
arr[arr>10] # like filter

array([85, 75, 16, 70, 32, 16, 34, 76, 97, 81, 56, 35, 42, 81, 16, 97, 62,
       42, 65, 53, 78, 30, 12, 54])

In [174]:
arr1 = np.random.randint(1,4,(5,5))
arr2 = np.random.randint(1,4,(5,5))

In [176]:
arr1

array([[3, 2, 1, 2, 3],
       [2, 3, 1, 2, 2],
       [3, 2, 3, 3, 3],
       [3, 3, 1, 3, 3],
       [3, 3, 2, 2, 2]])

In [177]:
arr2

array([[3, 3, 2, 2, 2],
       [1, 2, 1, 2, 1],
       [1, 3, 3, 1, 3],
       [1, 1, 2, 1, 1],
       [3, 2, 2, 3, 1]])

In [175]:
arr1 * arr2 # not a matrix multiplication, simple multiplication of element at same loc

array([[9, 6, 2, 4, 6],
       [2, 6, 1, 4, 2],
       [3, 6, 9, 3, 9],
       [3, 3, 2, 3, 3],
       [9, 6, 4, 6, 2]])

In [178]:
arr1 @ arr2 # matrix multiplication 

array([[23, 24, 21, 22, 16],
       [18, 21, 18, 19, 14],
       [26, 31, 29, 25, 23],
       [25, 27, 24, 25, 18],
       [22, 27, 23, 22, 19]])

In [179]:
arr2**2 # square of each element

array([[9, 9, 4, 4, 4],
       [1, 4, 1, 4, 1],
       [1, 9, 9, 1, 9],
       [1, 1, 4, 1, 1],
       [9, 4, 4, 9, 1]], dtype=int32)

In [181]:
arr = np.zeros((3,4))

In [182]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [187]:
a =  np.array([1,2,3,4])

In [188]:
arr + a # Columns wise Broadcasting 1D array on 2D array i.e for all rows

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [189]:
arr + 5 # simmilarly column Broadcasting using one number 

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [190]:
b =  np.array([1,2,3])

In [191]:
b.reshape(3,1)

array([[1],
       [2],
       [3]])

In [192]:
b.reshape(3,1) + arr # Row wise broadcasting 

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [193]:
b =  np.array([[1,2,3]])

In [194]:
b.T # Transposing (this requires multi dimensional array)

array([[1],
       [2],
       [3]])

In [195]:
b.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [196]:
arr = np.random.rand(2,4)

In [197]:
np.sqrt(arr)

array([[0.58838369, 0.43701139, 0.37991485, 0.80131939],
       [0.70064909, 0.28148381, 0.74307071, 0.60836025]])

In [198]:
np.exp(arr)

array([[1.41367877, 1.21043398, 1.1552714 , 1.90049194],
       [1.63380091, 1.08245665, 1.73699061, 1.44788257]])

In [200]:
np.log10(np.random.randint(2,5,(5,5)))

array([[0.47712125, 0.60205999, 0.30103   , 0.60205999, 0.60205999],
       [0.60205999, 0.60205999, 0.60205999, 0.47712125, 0.47712125],
       [0.30103   , 0.60205999, 0.60205999, 0.47712125, 0.30103   ],
       [0.30103   , 0.47712125, 0.47712125, 0.60205999, 0.47712125],
       [0.60205999, 0.60205999, 0.30103   , 0.47712125, 0.47712125]])

In [213]:
np.random.seed(15) # by this will get same value each time (can use any int number as seed)
np.random.rand(2,5)

array([[0.8488177 , 0.17889592, 0.05436321, 0.36153845, 0.27540093],
       [0.53000022, 0.30591892, 0.30447436, 0.11174128, 0.24989901]])