In [2]:
import pandas as pd
import numpy as np
# from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, roc_curve, roc_auc_score
from sklearn.preprocessing import StandardScaler
from pandas_profiling import ProfileReport
from sklearn.neighbors import KNeighborsClassifier
import pickle
# from sklearn.ensemble import BaggingClassifier
# from sklearn.ensemble import RandomForestClassifier

In [3]:
df = pd.read_csv('datasets/winequality_red.csv')
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [36]:
x = df.drop(columns=['quality'])
y = df.quality

x_train, x_test,y_train,y_test = train_test_split(x,y,random_state=20)#by defualt train size 75%


In [37]:
knn = KNeighborsClassifier()

In [38]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [39]:
knn.score(x_test,y_test)

0.5175

In [24]:
params = {
    'n_neighbors' : [3,5,7,9,12,13,15,17,21],
    'weights' : ['uniform', 'distance'],
    'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'leaf_size' : range(10,50,5), #for kd_tree and ball_tree
    'p' : [1,2] #to determine distance calcaultion 
}

In [25]:
grid_knn = GridSearchCV(knn,param_grid=params)

In [26]:
grid_knn.fit(x_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': range(10, 40, 2),
                         'n_neighbors': [3, 5, 7, 9, 12, 13, 15, 17, 21],
                         'p': [1, 2], 'weights': ['uniform', 'distance']})

In [27]:
grid_knn.best_params_

{'algorithm': 'auto',
 'leaf_size': 10,
 'n_neighbors': 21,
 'p': 1,
 'weights': 'distance'}

In [40]:
knn_best = KNeighborsClassifier(n_neighbors=21,weights='distance',algorithm='auto',leaf_size=10,p=1)
knn_best.fit(x_train,y_train)
knn_best.score(x_test,y_test)

0.6325

In [44]:
pickle.dump(knn,open("knn.pkl","wb"))
pickle.dump(knn_best,open("knn_gridcv.pkl","wb"))

In [47]:
ls

 Volume in drive D is DATA
 Volume Serial Number is 0EE1-4E94

 Directory of D:\ineuron\ineuron\Practice\ML_Practice

10-10-2021  16:05    <DIR>          .
10-10-2021  16:05    <DIR>          ..
10-10-2021  16:05    <DIR>          .ipynb_checkpoints
29-08-2021  16:40               548 admission_lr_model.pickle
29-08-2021  15:37         4,663,551 Admission_Prediction.html
22-08-2021  16:14               481 Advertise_linear_reg.sav
22-08-2021  15:43         1,666,385 Advertising_Reprot.html
29-09-2021  22:47    <DIR>          datasets
10-10-2021  15:22         1,780,618 DecisionTreePractice.ipynb
18-09-2021  00:12         7,628,008 diabetes_Reprot.html
29-09-2021  22:35        11,301,889 DT discussion not yet completed .ipynb
29-09-2021  23:50            57,546 dt_en_meta.dot
23-09-2021  23:48            78,749 HousingModelPractice.ipynb
10-10-2021  16:05            14,406 KNN Practice.ipynb
10-10-2021  16:04           239,761 knn.pkl
10-10-2021  16:04           253,076 knn_gridcv.pkl
1

In [51]:
x_test.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1508            7.1              0.27         0.60             2.1      0.074   
718             8.4              0.56         0.04             2.0      0.082   
1370            8.7              0.78         0.51             1.7      0.415   
579            10.6              0.31         0.49             2.2      0.063   
498            10.7              0.35         0.53             2.6      0.070   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1508                 17.0                  25.0  0.99814  3.38       0.72   
718                  10.0                  22.0  0.99760  3.22       0.44   
1370                 12.0                  66.0  0.99623  3.00       1.17   
579                  18.0                  40.0  0.99760  3.14       0.51   
498                   5.0                  16.0  0.99720  3.15       0.65   

      alcohol  
1508     10.6  
718       9.6  
1370      9.2  
579       9.8  
498      11.0

In [52]:
y_test.head()

1508    6
718     5
1370    5
579     6
498     8
Name: quality, dtype: int64

In [50]:
knn_best.predict([x_test.iloc[0]])

array([6], dtype=int64)

In [54]:
knn_best.predict([x_test.iloc[3]])

array([5], dtype=int64)

In [53]:
knn_best.predict([x_test.iloc[4]])

array([5], dtype=int64)

# SVM Support Vecotor Machine Classification

In [55]:
from sklearn.svm import SVC

In [56]:
svc =  SVC()
svc.fit(x_train,y_train)
svc.score(x_test,y_test)

0.5

In [ ]:
svc_params = {
    'kernel' : ['linear', 'poly', 'rbf', 'sigmoid'],
    'C' : [.1, .5,1,2,3,4],
    'gamma': [.001,.1,.4,.004,.003]
}

grid_svc = GridSearchCV(svc,param_grid=svc_params,verbose=3)
grid_svc.fit(x_train,y_train)

Fitting 5 folds for each of 120 candidates, totalling 600 fits
[CV] C=0.1, gamma=0.001, kernel=linear ...............................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ... C=0.1, gamma=0.001, kernel=linear, score=0.600, total=   0.4s
[CV] C=0.1, gamma=0.001, kernel=linear ...............................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.3s remaining:    0.0s


[CV] ... C=0.1, gamma=0.001, kernel=linear, score=0.525, total=   0.5s
[CV] C=0.1, gamma=0.001, kernel=linear ...............................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.7s remaining:    0.0s


[CV] ... C=0.1, gamma=0.001, kernel=linear, score=0.575, total=   0.3s
[CV] C=0.1, gamma=0.001, kernel=linear ...............................
[CV] ... C=0.1, gamma=0.001, kernel=linear, score=0.600, total=   0.3s
[CV] C=0.1, gamma=0.001, kernel=linear ...............................
[CV] ... C=0.1, gamma=0.001, kernel=linear, score=0.548, total=   0.5s
[CV] C=0.1, gamma=0.001, kernel=poly .................................
[CV] ..... C=0.1, gamma=0.001, kernel=poly, score=0.517, total=   0.2s
[CV] C=0.1, gamma=0.001, kernel=poly .................................
[CV] ..... C=0.1, gamma=0.001, kernel=poly, score=0.500, total=   0.2s
[CV] C=0.1, gamma=0.001, kernel=poly .................................
[CV] ..... C=0.1, gamma=0.001, kernel=poly, score=0.479, total=   0.2s
[CV] C=0.1, gamma=0.001, kernel=poly .................................
[CV] ..... C=0.1, gamma=0.001, kernel=poly, score=0.483, total=   0.1s
[CV] C=0.1, gamma=0.001, kernel=poly .................................
[CV] .

In [64]:
grid_svc.best_params_

AttributeError: 'GridSearchCV' object has no attribute 'best_params_'

In [58]:
svc_best = SVC(kernel='linear')
svc_best.fit(x_train,y_train)
svc_best.score(x_test,y_test)

0.5925

# SVM Regression

In [4]:
data = pd.read_csv('datasets/Admission_Prediction.csv')
data

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1      337.0        118.0                4.0  4.5  4.5  9.65   
1             2      324.0        107.0                4.0  4.0  4.5  8.87   
2             3        NaN        104.0                3.0  3.0  3.5  8.00   
3             4      322.0        110.0                3.0  3.5  2.5  8.67   
4             5      314.0        103.0                2.0  2.0  3.0  8.21   
..          ...        ...          ...                ...  ...  ...   ...   
495         496      332.0        108.0                5.0  4.5  4.0  9.02   
496         497      337.0        117.0                5.0  5.0  5.0  9.87   
497         498      330.0        120.0                5.0  4.5  5.0  9.56   
498         499      312.0        103.0                4.0  4.0  5.0  8.43   
499         500      327.0        113.0                4.0  4.5  4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [9]:
data.isna().sum()

Serial No.            0
GRE Score            15
TOEFL Score          10
University Rating    15
SOP                   0
LOR                   0
CGPA                  0
Research              0
Chance of Admit       0
dtype: int64

In [15]:
for col in data.columns:
    if(data[col].isna().sum() > 0):
        data[col] = data[col].fillna(data[col].mean())

In [16]:
data.isna().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [17]:
y = data['Chance of Admit']
x = data.drop(columns=['Chance of Admit'])

x_train, x_test,y_train,y_test = train_test_split(x,y,random_state=30,test_size=.20)#by defualt train size 75%


In [18]:
from sklearn.svm import SVR

In [19]:
svr = SVR()
svr.fit(x_train,y_train)

SVR()

In [21]:
from sklearn.metrics import r2_score
r2_score(y_test,svr.predict(x_test))

0.611650659631894

In [27]:
svr.predict([x.iloc[1]])

array([0.69204653])

In [28]:
y[1]

0.76

In [30]:
svr.score(x_test,y_test) # here function is same but in regression it is a result of r square 
# and in case of classification it gives accuracy value 

0.611650659631894

# Stacking 

In [35]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, roc_curve, roc_auc_score
from sklearn.preprocessing import StandardScaler
from pandas_profiling import ProfileReport
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import pickle

In [36]:
df1 = pd.read_csv('datasets/winequality_red.csv')
df1

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [37]:
x = df1.drop(columns='quality')
y = df1.quality

In [41]:
# dividing data first in validation and train
train , val_train , test, val_test = train_test_split(x,y,test_size = .50 , random_state = 30)

In [42]:
# now train data again split into train and test 
x_train , x_test , y_train, y_test = train_test_split(train,test,test_size = .15 , random_state = 30)

In [43]:
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)
knn.score(x_test,y_test)

0.5833333333333334

In [44]:
svc = SVC()
svc.fit(x_train,y_train)
svc.score(x_test,y_test)

0.5083333333333333

In [45]:
knn_pred = knn.predict(val_train)
svc_pred = svc.predict(val_train)

In [49]:
# now will treat this predictions from knn and svc model as a input feature for another model 
# keeping val_test as label for training 3 rd model 

# stacking both the predictions as a DF
input_df = pd.DataFrame(np.column_stack((knn_pred,svc_pred)))
input_df

0  1
0    7  6
1    5  6
2    6  6
3    5  6
4    5  6
..  .. ..
795  5  6
796  5  6
797  6  6
798  6  6
799  5  5

[800 rows x 2 columns]

In [51]:
output = val_test
output

1147    7
659     4
871     5
1333    5
1411    6
       ..
1073    6
200     7
942     7
1106    6
1329    6
Name: quality, Length: 800, dtype: int64

In [52]:
# now can select RandomForest as a 3 rd model

rf =RandomForestClassifier()
rf.fit(input_df,output)

RandomForestClassifier()

In [56]:
# now for final prediction we need model 1 and model 2 prediction combined as x_test 
# and y_test expected label value 
rf.score(np.column_stack((knn.predict(x_test),svc.predict(x_test))),y_test)

0.5833333333333334