In [1]:
!pip install joblib

In [ ]:
# ref -> https://github.com/c17hawke/Perceptron_implimentation_FSDS
# DL intro collab notebook -> https://colab.research.google.com/drive/12n3MwGahkQZuTi4fDhYja2-AcyBsuQKc

In [25]:
import os 
import matplotlib.pyplot as plt
import joblib
import numpy as np
import  pandas as pd

plt.style.use("fivethirtyeight")

In [3]:
np.random.randn(3)

array([ 0.07879254, -0.44381755,  1.09172885])

In [17]:
1e-4 #indicates => 10^-4

0.0001

In [18]:
 np.random.randn(3) * 1e-4 

array([-1.10487856e-04,  3.47306165e-05, -6.55591755e-05])

In [12]:
np.c_[[[12, 23],
      [34, 45]],-np.ones((2,1))]

array([[12., 23., -1.],
       [34., 45., -1.]])

In [67]:

class Perceptron:
    
    def __init__(self,eta: float=None,epochs: int=None):
        #self.weights = np.random.randn(3) * 1e-4 
        self.eta=eta # learning rate
        self.epochs = epochs # iterations
        
    #_ for private function
    def _z_outcomes(self, inputs, weights): 
        return np.dot(inputs,weights) # for dot product of matrix
    
    
    def activation_function(self,z):
        #step funtion considering 0 as threshold if >0 then 1 else 0
        return np.where(z>0,1,0) 
    
    def fit(self,x,y):
        self.x = x
        self.y = y
        self.weights = np.random.randn(self.x.shape[1]+1) * 1e-4 
            
        x_with_bias = np.c_[self.x,-np.ones((len(self.x),1))]
        print(f"X with Bias:\n{x_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {epoch + 1}")
            print("--"*10)
            z = self._z_outcomes(x_with_bias,self.weights)
            y_hat = self.activation_function(z)
            print(f"y_hat :\n{y_hat} for epoch {epoch+1}/{self.epochs}")
            
            self.error = y - y_hat
            print(f"error: \n{self.error}")
            
            if(np.all((self.error == 0))): # for early exit 
                break
                
            self.weights = self.weights + self.eta * np.dot(x_with_bias.T,self.error)
            print(f"updated weights after epoch: {epoch + 1}/{self.epochs}: \n{self.weights}")
            print(f"##"*10)
            
    
    def predict(self,x):
        x_with_bias = np.c_[x,-np.ones((len(x),1))]
        z = self._z_outcomes(x_with_bias,self.weights)
        y_pred = self.activation_function(z)
        return y_pred
            
        
        

In [68]:
x =  np.ones((4,1))
x.shape

(4, 1)

In [69]:
df_OR = pd.DataFrame({
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,1]
})

In [70]:
def prepare_data(df,target_col="y"):
    x = df.drop(target_col,axis=1)
    y= df[target_col]
    
    return x,y

In [71]:
x, y = prepare_data(df_OR)
eta=0.1
ephocs=10

model_or = Perceptron(eta=eta,epochs=ephocs)
model_or.fit(x,y)

X with Bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
y_hat :
[0 1 1 1] for epoch 1/10
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64


In [72]:
model_or.predict([[0,1]])

array([1])

In [73]:
model_or.predict([[1,1]])

array([1])

In [74]:
model_or.predict([[0,0]])

array([0])

In [75]:
df_AND = pd.DataFrame({
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,0,0,1]
})

x, y = prepare_data(df_AND)
eta=0.1
ephocs=10

model_and = Perceptron(eta=eta,epochs=ephocs)
model_and.fit(x,y)

model_and.predict([[0,1]])

X with Bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
y_hat :
[1 1 1 1] for epoch 1/10
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[-0.09987593 -0.10003623  0.29992753]
####################
--------------------
for epoch >> 2
--------------------
y_hat :
[0 0 0 0] for epoch 2/10
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 1.24068836e-04 -3.62305298e-05  1.99927532e-01]
####################
--------------------
for epoch >> 3
--------------------
y_hat :
[0 0 0 0] for epoch 3/10
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[0.10012407 0.09996377 0.09992753]
####################
--------------------
for epoch >> 4
--------------------
y_hat :
[0 1 1 1] for epoch 4/10
error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 4/10: 
[ 1.

array([0])

In [76]:
model_and.predict([[1,1]])

array([1])

In [77]:
# same wont work for XOR as it is not having linear behavior for it will require multiple neurons\perceptron

df_XOR = pd.DataFrame({
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,0]
})

x, y = prepare_data(df_XOR)
eta=0.1
ephocs=10

model_xor = Perceptron(eta=eta,epochs=ephocs)
model_xor.fit(x,y)

model_xor.predict([[0,1]])

X with Bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 1
--------------------
y_hat :
[1 1 1 1] for epoch 1/10
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[-0.09995988 -0.09982267  0.19989827]
####################
--------------------
for epoch >> 2
--------------------
y_hat :
[0 0 0 0] for epoch 2/10
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 4.01178083e-05  1.77331537e-04 -1.01732711e-04]
####################
--------------------
for epoch >> 3
--------------------
y_hat :
[1 1 1 1] for epoch 3/10
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[-0.09995988 -0.09982267  0.19989827]
####################
--------------------
for epoch >> 4
--------------------
y_hat :
[0 0 0 0] for epoch 4/10
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 4/10: 
[

array([1])