In [46]:
#Q1 To add two matrix
import numpy as np
a = [[12,20,45,1],
    [45,3,6,2],
    [2,14,65,3]]

b = [[10,30,5,33],
    [2,12,1,70],
    [22,54,25,32]]

In [47]:
# addition of matix by converting to numpy array
np.array(a) + np.array(b)

array([[22, 50, 50, 34],
       [47, 15,  7, 72],
       [24, 68, 90, 35]])

In [48]:
#Q2 To multiply two matrix
np.array(a) * np.array(b)

array([[ 120,  600,  225,   33],
       [  90,   36,    6,  140],
       [  44,  756, 1625,   96]])

In [58]:
a = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
   
b = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]

def matrixmul(a,b):
    
    if(len(a[0]) == len(b) or len(b[0]) == len(a)): 
        result = list()  
        for i in range(len(a)):
            res = list()
            for j in range(len(b[0])):   
                s = 0
                for k in range(len(b)):
                    s  += a[i][k] * b[k][j]
                    
                res.append(s)
            result.append(res)
        return np.array(result)
    else:
        return 'Cannot multiply matrices as they r not of correct length'
    
print(matrixmul(a,b))

[[114 160  60  27]
 [ 74  97  73  14]
 [119 157 112  23]]


In [60]:
print(matrixmul(a,b))

[[ 99  83  72]
 [121 101  87]
 [131 125 123]]


In [62]:
#Q3. Transpose of matrix
np.array(a).T

array([[5, 6, 4],
       [8, 7, 5],
       [1, 3, 9],
       [2, 0, 1]])

In [101]:
#Q4. To sort words in alphabetical order
def wsort(sentence):
    jnStr =" "
    lst = sorted(sentence.split(" "))
    print(jnStr.join(lst))
wsort('ggfd bsde atul cfg zsr desf hello')

atul bsde cfg desf ggfd hello zsr


In [105]:
# Q4 To remove punctuation from string
import string 
def remPunctuatio(sent):
    res=""
    for word in sent.split(" "):
        if word in string.punctuation:
            continue
        res += word + " "
    return res

remPunctuatio('Hello world !')

'Hello world '